name: Update PUBG Stats

on:
  schedule:
    - cron: "*/5 * * * *"  # jede 5 min
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install axios

      - run: node update.js
        env:
          PUBG_KEY: ${{ secrets.PUBG_KEY }}

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add stats.json
          git commit -m "Update stats"
          git push